### ISSUE TITLE
create method for generate random generic Objects

### ISSUE THREAD

**Issue by tatjana19** [astrapi69/randomizer#2]
It would be nice to have a method that generates  random generic Objects over a Class object from this Object. This could be done with reflection. For instance with the class

 https://commons.apache.org/proper/commons-lang/apidocs/index.html?org/apache/commons/lang3/reflect/FieldUtils.html

**Comment by jimmyMaci** [comment]
@tatjana19 this you can achieve over the random-beans project. I think this library is only for specific random objects.

**Comment by astrapi69** [comment]
@jimmyMaci is right, i will close this issue
